### ISSUE TITLE
EvcsController unable to set certain channel values from child evcs component

### ISSUE THREAD

**Issue by marcelheim** [OpenEMS/openems#1197]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Bug description or desired functionality.

Version: 2020.16.0 (Release)
Afftected component: io.openems.edge.controller.evcs
Source: [EvcsController.java](../blob/master/io.openems.edge.controller.evcs/src/io/openems/edge/controller/evcs/EvcsController.java) after commit openems@641d048
#### Description
Channels SET_ENERGY_LIMIT, SET_CHARGE_POWER_REQUEST, SET_CHARGE_POWER_LIMIT aren't set properly by methods setEnergyLimit(), setChargePowerRequest() and setChargePowerLimit() in used evcs component
 
#### Example code from [EvcsController.java](../blob/master/io.openems.edge.controller.evcs/src/io/openems/edge/controller/evcs/EvcsController.java)
```java
if (!config.enabledCharging()) {
	evcs.setChargePowerLimit(0);
	return;
}
```

#### Possible fix
Call internal set funtion
```java
if (!config.enabledCharging()) {
	evcs._setChargePowerLimit(0);
	return;
}
```

**Comment by sebastianasen** [comment]
Hallo @marcelheim,
thank you for creating this issue.

Do you use the EvcsController in combination with an EvcsCluster?
Only here, i found the bug that an old requested charge power is still preset.

Because of that, the cluster is setting also the setChargePowerLimit (to the old value).
This will be fixed in the next pull request wich i will mention in here.

---
For your information:
The _setChargePowerLimit will set the "value" of the Channel "SetChargePowerLimit". This value is only used for displaying the current target we sent.

The setChargePowerLimit will set per defenition the "write value" of the Channel. 
In every Chargingstation i will react on the WriteValue and will reset it afterwards. Only that Value will be forwarded to the chargingstation.
