### ISSUE TITLE
Put the software into a cloud server

### ISSUE THREAD

**Issue by wins2020** [OpenEMS/openems#1628]
Hello 
I would like to know how I can put the software on a cloud server 
also, it's allowed to change something in the code, and start working with it, there is any copyrights or something illegal?
also, how can i get the App on Android and ios?

Thanks for your services.

**Comment by sfeilmeier** [comment]
Hi,
I can recommend to ask your questions to the OpenEMS Community at https://community.openems.io/. Also the OpenEMS Docs should be helpful: https://openems.github.io/openems.io/openems/latest/introduction.html

Regarding your questions:
- Cloud server. See
  - https://openems.github.io/openems.io/openems/latest/backend/build.html
  - https://openems.github.io/openems.io/openems/latest/backend/deploy.html
  - https://community.openems.io/t/how-to-install-openems-production-ready/607
- Copyrights/License:
  - See https://github.com/OpenEMS/openems/blob/develop/README.md
  - OpenEMS Edge and Backend are licensed under Eclipse Public License version 2.0.
  - OpenEMS UI is licensed under GNU Affero General Public License version 3.
- App for Android/iOS
  - It can be installed as a webapp. See docs for FEMS (using OpenEMS UI) for details: https://docs.fenecon.de/de/_/latest/fems/ui/introduction.html#_als_app_auf_smartphonetablet_hinzuf%C3%BCgen

I am closing this here for now, because it is not actually an issue.

Regards,
Stefan
