### ISSUE TITLE
Metadata.File: Example has wrong Format

### ISSUE THREAD

**Issue by obel1x** [OpenEMS/openems#1825]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting: Did that [x]
```

### Bug description or desired functionality.

The Readme.md [here](https://github.com/OpenEMS/openems/tree/develop/io.openems.backend.metadata.file) does not work and returns errors when loading the backend:

```
May 15 18:08:48 obel1x java[32224]: io.openems.backend.metadata.file [io.openems.backend.metadata.file.FileMetadata] WARN : [Metadata.File] Unable to JSON-parse file [/etc/openems-backend.d/metadata.json]: JSON [setuppassword] is not a member of [{"comment":"Edge #0","apikey":"edge0"}]
May 15 18:08:48 obel1x java[32224]: io.openems.common.exceptions.OpenemsError$OpenemsNamedException: JSON [setuppassword] is not a member of [{"comment":"Edge #0","apikey":"edge0"}]

```
the working format is (e.g. - no quotes)
```
{
    edges: {
        edge0: {
            apikey: "test",
            setuppassword: "test",
            comment: "OpenEMS Demo Edge"
        }
    }
}
```

**Comment by sfeilmeier** [comment]
Thanks for reporting! The actual problem was the missing `setuppassword` - see my comment here: https://community.openems.io/t/error-when-connecting-the-edge-to-backend/787/9?u=stefan.feilmeier

I tested both JSON formats with and without quotation marks and both are properly parsed by OpenEMS using the GSON library.

I updated the logic to make the `setuppassword` optional.
