### ISSUE TITLE
more detailled informations over REST API

### ISSUE THREAD

**Issue by ornago** [OpenEMS/openems#1992]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Bug description or desired functionality.
In the "FEMS Online-Monitoring" is a visualization of the "EmergencyPowerMeter" component. How can I get this data from the REST Api or ModBus? The only REST component in your documentation is "_sum", are there more? If not, I would love it, if you implement more.
![grafik](https://user-images.githubusercontent.com/12096794/204086923-362af050-ef65-4098-9833-3a653cf10f5e.png)

**Comment by sfeilmeier** [comment]
Hi Ornago,

in general please consider contacting the FENECON support if you have questions about FENECON products or FEMS: https://fenecon.de/kontakt/
For general questions about OpenEMS we recommend the OpenEMS Community: https://community.openems.io

I am closing the issue here for this reason.

But to still give you a hint in the right direction: in FENECON Online-Monitoring open "Einstellungen" -> "Anlagenprofil" to get a list of all configured components. (direct link: https://portal.fenecon.de/m/device/<FEMS-Nr>/settings/profile. Lookup the internale Component-ID of the emergency power meter; this will often be `meter2` for a FENECON Home system. To receive the power value of the meter, you can then query `meter2/ActivePower` via the REST-Api. The value is not available by default via the Modbus/TCP interface.

Regards,
Stefan
