### ISSUE TITLE
Supports can protocol

### ISSUE THREAD

**Issue by luckyfisher** [OpenEMS/openems#2276]
In some business, the function of CAN will be used. Can we add support for CAN?

**Comment by clehne** [comment]
Hi luckyfisher, we already have a CAN Bridge which is working almost like the Modbus Bridge. It uses the CAN Socket API. A library for Kunbus RevolutionPi (with CAN extension) is already included. The CAN bridge is not yet published, because we can't provide an Open Source driver, which uses the bridge. This makes it a bit complicated to use the CAN brdige. Nevertheless I will make a PR of the bundle by next week.

**Comment by luckyfisher** [comment]
Thanks

**Comment by sfeilmeier** [comment]
I know that also @hydroid7 has been working on a CAN implementation. Maybe he can share it as well.

@luckyfisher: the OpenEMS Community Forum might be a better fit for questions like this: https://community.openems.io Could you possibly ask the question again over there? I am closing the issue here.
