### ISSUE TITLE
Enhance ToU Controller V2 to Consider Emergency Reserve in SoC Calculations

### ISSUE THREAD

**Issue by Sn0w3y** [OpenEMS/openems#2883]
### Component

Edge

### Description

Currently, the Time-of-Use (ToU) Controller assumes that the Storage State of Charge (SoC) will always go down to 0% at the end of its calculation horizon. However, this approach does not take into account the Emergency Reserve configuration, leading to inaccurate projections and suboptimal operational strategies. The ToU Controller should be enhanced to recognize and factor in the configured Emergency Reserve, ensuring more accurate and realistic SoC predictions.

**Comment by sfeilmeier** [comment]
I don't think this is actually true, because configured Min-SoC is considered already. See [develop](https://github.com/OpenEMS/openems/blob/develop/io.openems.edge.controller.ess.timeofusetariff/src/io/openems/edge/controller/ess/timeofusetariff/v1/UtilsV1.java#L37-L58)

Can you somehow "prove" your observations, e.g. with a Screenshot or better the ToU Debug-log?

**Comment by sfeilmeier** [comment]
V2 is currently still under heavy development. The way Emergency Backup SoC is applied in V2 is completely different compared to V1. V2 just merged to develop already to give the community some insight on where development heads to... please don't use it in production yet. 

For V1 it should work properly. And your GoodWe+BYD setup should not make a difference. Good to know, this works for you ;-)

Detailed logs can be configured here: https://github.com/OpenEMS/openems/blob/develop/io.openems.edge.energy/src/io/openems/edge/energy/Config.java#L16-L17

With those logs you can even "re-run" the simulation using the "RunOptimizerFromLogApp": https://github.com/OpenEMS/openems/blob/develop/io.openems.edge.energy/test/io/openems/edge/energy/optimizer/app/RunOptimizerFromLogApp.java

**Comment by sfeilmeier** [comment]
There are also some additional lines before in the log. As suggested in [RunOptimizerFromLogApp.java](https://github.com/OpenEMS/openems/blob/develop/io.openems.edge.energy/test/io/openems/edge/energy/optimizer/app/RunOptimizerFromLogApp.java#L28-L41) (for V2) and [RunOptimizerFromLogV1App ](https://github.com/OpenEMS/openems/blob/develop/io.openems.edge.energy/test/io/openems/edge/energy/v1/optimizer/RunOptimizerFromLogV1App.java#L7-L20), use the following command to filter the full log:

`journalctl -lu openems --since="20 minutes ago" | grep OPTIMIZER`

The header lines will tell you more about the system, existing Controllers, etc.
